/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on Oct 23, 2017, 10:59:09 AM
 */
package lab4;

import java.util.Hashtable;
import javax.swing.JLabel;

/**
 *
 * @author user
 */
public class NewJFrame extends javax.swing.JFrame {

    Presets[] presets = new Presets[3];
    
    int currentSelected = 0;
    
    public void setupPresets()
    {
        presets[0] = new Presets(0, 0, 0, 0, 0);
        presets[1] = new Presets(1, -1, 9, 0, 4);
        presets[2] = new Presets(2, 4, -2, 4, 2);
    }
    
    public void showSliderValues()
    {
        info.setText("<html>Bass: " + SBass.getValue() +
                     "<br>Midrange: " + SMidrange.getValue() +
                     "<br>Tremble: " + STremble.getValue() + 
                     "<br>Balance: " + (SBalance.getValue() < 0 ? "Left" : (SBalance.getValue() == 0) ? "Center" : "Right") +
                     "<br>Volume: " + SVolume.getValue());
    }
    
    public void loadPresets(int i)
    {
        SBass.setValue(presets[i].getSBass());
        SMidrange.setValue(presets[i].getSMidrange());
        STremble.setValue(presets[i].getSTremble());
        SBalance.setValue(presets[i].getSBalance());
        SVolume.setValue(presets[i].getSVolume());
    }
    
    public void savePresets(int i)
    {
        presets[i].setSBass(SBass.getValue());
        presets[i].setSMidrange(SMidrange.getValue());
        presets[i].setSTremble(STremble.getValue());
        presets[i].setSBalance(SBalance.getValue());
        presets[i].setSVolume(SVolume.getValue());
    }
    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
        setSize(550, 600);
        
        setupPresets();
        loadPresets(currentSelected);
        showSliderValues();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        LBass = new javax.swing.JLabel();
        LMidrange = new javax.swing.JLabel();
        LTremble = new javax.swing.JLabel();
        LBalance = new javax.swing.JLabel();
        LVolume = new javax.swing.JLabel();
        info = new javax.swing.JLabel();
        SBass = new javax.swing.JSlider();
        SMidrange = new javax.swing.JSlider();
        STremble = new javax.swing.JSlider();
        SBalance = new javax.swing.JSlider();
        SVolume = new javax.swing.JSlider();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Audio Player");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        LBass.setText("Bass");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        getContentPane().add(LBass, gridBagConstraints);

        LMidrange.setText("Midrange");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(LMidrange, gridBagConstraints);

        LTremble.setText("Tremble");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        getContentPane().add(LTremble, gridBagConstraints);

        LBalance.setText("Balance");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        getContentPane().add(LBalance, gridBagConstraints);

        LVolume.setText("Volume");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        getContentPane().add(LVolume, gridBagConstraints);

        info.setText("jLabel6");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        getContentPane().add(info, gridBagConstraints);

        SBass.setMajorTickSpacing(2);
        SBass.setMaximum(10);
        SBass.setMinimum(-10);
        SBass.setMinorTickSpacing(1);
        SBass.setPaintLabels(true);
        SBass.setPaintTicks(true);
        SBass.setValue(0);
        SBass.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        SBass.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SBassStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        getContentPane().add(SBass, gridBagConstraints);

        SMidrange.setMajorTickSpacing(2);
        SMidrange.setMaximum(10);
        SMidrange.setMinimum(-10);
        SMidrange.setMinorTickSpacing(1);
        SMidrange.setPaintLabels(true);
        SMidrange.setPaintTicks(true);
        SMidrange.setValue(0);
        SMidrange.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        SMidrange.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SMidrangeStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        getContentPane().add(SMidrange, gridBagConstraints);

        STremble.setMajorTickSpacing(2);
        STremble.setMaximum(10);
        STremble.setMinimum(-10);
        STremble.setMinorTickSpacing(1);
        STremble.setPaintLabels(true);
        STremble.setPaintTicks(true);
        STremble.setValue(0);
        STremble.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        STremble.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                STrembleStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        getContentPane().add(STremble, gridBagConstraints);

        table.put(new Integer(0), new JLabel("Center"));
        table.put(new Integer(-5), new JLabel("L"));
        table.put(new Integer(5), new JLabel("R"));
        SBalance.setLabelTable(table);
        SBalance.setMajorTickSpacing(2);
        SBalance.setMaximum(5);
        SBalance.setMinimum(-5);
        SBalance.setMinorTickSpacing(1);
        SBalance.setPaintLabels(true);
        SBalance.setPaintTicks(true);
        SBalance.setValue(0);
        SBalance.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        SBalance.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SBalanceStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        getContentPane().add(SBalance, gridBagConstraints);

        SVolume.setMajorTickSpacing(1);
        SVolume.setMaximum(10);
        SVolume.setPaintLabels(true);
        SVolume.setPaintTicks(true);
        SVolume.setValue(0);
        SVolume.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        SVolume.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SVolumeStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        getContentPane().add(SVolume, gridBagConstraints);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("M0");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        getContentPane().add(jRadioButton1, gridBagConstraints);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("M1");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        getContentPane().add(jRadioButton2, gridBagConstraints);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("M2");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        getContentPane().add(jRadioButton3, gridBagConstraints);

        jButton1.setText("Store");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        getContentPane().add(jButton1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
loadPresets(2);
currentSelected = 2;// TODO add your handling code here:
}//GEN-LAST:event_jRadioButton3ActionPerformed

private void SBassStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SBassStateChanged
showSliderValues();// TODO add your handling code here:
}//GEN-LAST:event_SBassStateChanged

private void SMidrangeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SMidrangeStateChanged
showSliderValues();// TODO add your handling code here:
}//GEN-LAST:event_SMidrangeStateChanged

private void STrembleStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_STrembleStateChanged
showSliderValues();// TODO add your handling code here:
}//GEN-LAST:event_STrembleStateChanged

private void SBalanceStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SBalanceStateChanged
showSliderValues();// TODO add your handling code here:
}//GEN-LAST:event_SBalanceStateChanged

private void SVolumeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SVolumeStateChanged
showSliderValues();// TODO add your handling code here:
}//GEN-LAST:event_SVolumeStateChanged

private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
loadPresets(0);
currentSelected = 0;// TODO add your handling code here:
}//GEN-LAST:event_jRadioButton1ActionPerformed

private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
loadPresets(1);
currentSelected = 1;// TODO add your handling code here:
}//GEN-LAST:event_jRadioButton2ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
savePresets(currentSelected);// TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    
    Hashtable table = new Hashtable();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBalance;
    private javax.swing.JLabel LBass;
    private javax.swing.JLabel LMidrange;
    private javax.swing.JLabel LTremble;
    private javax.swing.JLabel LVolume;
    private javax.swing.JSlider SBalance;
    private javax.swing.JSlider SBass;
    private javax.swing.JSlider SMidrange;
    private javax.swing.JSlider STremble;
    private javax.swing.JSlider SVolume;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel info;
    private javax.swing.JButton jButton1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    // End of variables declaration//GEN-END:variables
}
