/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * lab5_1.java
 *
 * Created on Nov 6, 2017, 11:04:13 AM
 */
package lab5;

import javax.swing.ImageIcon;

/**
 *
 * @author user
 */
public class lab5_1 extends javax.swing.JFrame {

    /** Creates new form lab5_1 */
    public lab5_1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPHotel = new javax.swing.JPanel();
        jRBALArab = new javax.swing.JRadioButton();
        jRBHilton = new javax.swing.JRadioButton();
        jRBIceHotel = new javax.swing.JRadioButton();
        jPDetails = new javax.swing.JPanel();
        Breakfast = new javax.swing.JCheckBox();
        Dinner = new javax.swing.JCheckBox();
        ExtraTrip = new javax.swing.JCheckBox();
        jPRoom = new javax.swing.JPanel();
        JRBSimple = new javax.swing.JRadioButton();
        JRBDouble = new javax.swing.JRadioButton();
        JRBSuite = new javax.swing.JRadioButton();
        jBShowIcon = new javax.swing.JButton();
        jLRoomIcon = new javax.swing.JLabel();
        jPReport = new javax.swing.JPanel();
        jLHotel = new javax.swing.JLabel();
        jLRoom = new javax.swing.JLabel();
        jLDetails = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Holidays");

        buttonGroup1.add(jRBALArab);
        jRBALArab.setSelected(true);
        jRBALArab.setToolTipText("AL Arab Hotel");
        jRBALArab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab5/BurjAlArabHotelBW.jpg"))); // NOI18N
        jRBALArab.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/lab5/BurjAlArabHotel.jpg"))); // NOI18N
        jRBALArab.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/lab5/BurjAlArabHotel.jpg"))); // NOI18N
        jRBALArab.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/lab5/BurjAlArabHotel.jpg"))); // NOI18N
        jRBALArab.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRBALArabStateChanged(evt);
            }
        });
        jRBALArab.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRBALArabItemStateChanged(evt);
            }
        });

        buttonGroup1.add(jRBHilton);
        jRBHilton.setToolTipText("Hilton Hotel");
        jRBHilton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab5/hiltonhotelBW.jpg"))); // NOI18N
        jRBHilton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/lab5/hiltonhotel.jpg"))); // NOI18N
        jRBHilton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/lab5/hiltonhotel.jpg"))); // NOI18N
        jRBHilton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/lab5/hiltonhotel.jpg"))); // NOI18N
        jRBHilton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRBHiltonStateChanged(evt);
            }
        });
        jRBHilton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRBHiltonItemStateChanged(evt);
            }
        });

        buttonGroup1.add(jRBIceHotel);
        jRBIceHotel.setToolTipText("Ice Hotel");
        jRBIceHotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab5/icehotelBW.jpg"))); // NOI18N
        jRBIceHotel.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/lab5/icehotel.jpg"))); // NOI18N
        jRBIceHotel.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/lab5/icehotel.jpg"))); // NOI18N
        jRBIceHotel.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/lab5/icehotel.jpg"))); // NOI18N
        jRBIceHotel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRBIceHotelStateChanged(evt);
            }
        });
        jRBIceHotel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRBIceHotelItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPHotelLayout = new javax.swing.GroupLayout(jPHotel);
        jPHotel.setLayout(jPHotelLayout);
        jPHotelLayout.setHorizontalGroup(
            jPHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPHotelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRBALArab)
                    .addComponent(jRBHilton)
                    .addComponent(jRBIceHotel))
                .addContainerGap(274, Short.MAX_VALUE))
        );
        jPHotelLayout.setVerticalGroup(
            jPHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPHotelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRBALArab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRBHilton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRBIceHotel)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPHotel);

        jTabbedPane1.addTab("Hotels", jScrollPane1);

        Breakfast.setText("Breakfast");
        Breakfast.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                BreakfastStateChanged(evt);
            }
        });

        Dinner.setText("Dinner");
        Dinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                DinnerStateChanged(evt);
            }
        });

        ExtraTrip.setText("Extra Trip");
        ExtraTrip.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ExtraTripStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPDetailsLayout = new javax.swing.GroupLayout(jPDetails);
        jPDetails.setLayout(jPDetailsLayout);
        jPDetailsLayout.setHorizontalGroup(
            jPDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Breakfast)
                    .addComponent(Dinner)
                    .addComponent(ExtraTrip))
                .addContainerGap(296, Short.MAX_VALUE))
        );
        jPDetailsLayout.setVerticalGroup(
            jPDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Breakfast)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dinner)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExtraTrip)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Details", jPDetails);

        buttonGroup2.add(JRBSimple);
        JRBSimple.setSelected(true);
        JRBSimple.setText("Single");
        JRBSimple.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                JRBSimpleStateChanged(evt);
            }
        });

        buttonGroup2.add(JRBDouble);
        JRBDouble.setText("Double");
        JRBDouble.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                JRBDoubleStateChanged(evt);
            }
        });
        JRBDouble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBDoubleActionPerformed(evt);
            }
        });

        buttonGroup2.add(JRBSuite);
        JRBSuite.setText("Suite");
        JRBSuite.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                JRBSuiteStateChanged(evt);
            }
        });

        jBShowIcon.setText("Show Icon");
        jBShowIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBShowIconActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPRoomLayout = new javax.swing.GroupLayout(jPRoom);
        jPRoom.setLayout(jPRoomLayout);
        jPRoomLayout.setHorizontalGroup(
            jPRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRoomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JRBSimple)
                    .addComponent(JRBDouble)
                    .addComponent(JRBSuite)
                    .addGroup(jPRoomLayout.createSequentialGroup()
                        .addComponent(jLRoomIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(245, 245, 245))
                    .addGroup(jPRoomLayout.createSequentialGroup()
                        .addComponent(jBShowIcon)
                        .addContainerGap(282, Short.MAX_VALUE))))
        );
        jPRoomLayout.setVerticalGroup(
            jPRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRoomLayout.createSequentialGroup()
                .addGroup(jPRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPRoomLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(JRBDouble)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JRBSuite))
                    .addGroup(jPRoomLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(JRBSimple)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLRoomIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBShowIcon)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Room", jPRoom);

        jLHotel.setText("AL Arab Hotel");

        jLRoom.setText("Simple");

        jLDetails.setText("Options Selected:");

        javax.swing.GroupLayout jPReportLayout = new javax.swing.GroupLayout(jPReport);
        jPReport.setLayout(jPReportLayout);
        jPReportLayout.setHorizontalGroup(
            jPReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPReportLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLHotel)
                    .addComponent(jLRoom)
                    .addComponent(jLDetails))
                .addContainerGap(280, Short.MAX_VALUE))
        );
        jPReportLayout.setVerticalGroup(
            jPReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPReportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLHotel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLRoom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLDetails)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Report", jPReport);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

static int currentSelected = 0;

private void jBShowIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBShowIconActionPerformed
    switch(currentSelected)
    {
        case 0:
            if(JRBSimple.isSelected())
            {
                jLRoomIcon.setIcon(new ImageIcon("./src/lab5/AlArabRoom.jpg"));
            }
            else if(JRBDouble.isSelected())
            {
                jLRoomIcon.setIcon(new ImageIcon("./src/lab5/AlArabDouble.jpg"));
            }
            else
            {
                jLRoomIcon.setIcon(new ImageIcon("./src/lab5/AlArabSuite.jpg"));
            }
            break;
        case 1:
            if(JRBSimple.isSelected())
            {
                jLRoomIcon.setIcon(new ImageIcon("./src/lab5/HiltonSingle.jpg"));
            }
            else if(JRBDouble.isSelected())
            {
                jLRoomIcon.setIcon(new ImageIcon("./src/lab5/HiltonDouble.jpg"));
            }
            else
            {
                jLRoomIcon.setIcon(new ImageIcon("./src/lab5/HiltonSuite.jpg"));
            }
            break;
        case 2:
            if(JRBSimple.isSelected())
            {
                jLRoomIcon.setIcon(new ImageIcon("./src/lab5/IceHotelSingle.jpg"));
            }
            else if(JRBDouble.isSelected())
            {
                jLRoomIcon.setIcon(new ImageIcon("./src/lab5/IceHotelDouble.jpg"));
            }
            else
            {
                jLRoomIcon.setIcon(new ImageIcon("./src/lab5/IceHotelSuite.jpg"));
            }
            break;
    }
}//GEN-LAST:event_jBShowIconActionPerformed

private void JRBDoubleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBDoubleActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_JRBDoubleActionPerformed

private void jRBALArabStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRBALArabStateChanged

}//GEN-LAST:event_jRBALArabStateChanged

private void jRBHiltonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRBHiltonStateChanged

}//GEN-LAST:event_jRBHiltonStateChanged

private void jRBIceHotelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRBIceHotelStateChanged

}//GEN-LAST:event_jRBIceHotelStateChanged

public void updateOptions()
{
    String test = "Options Selected:";
    if(Breakfast.isSelected())
    {
        test += " Breakfast";
    }
    if(Dinner.isSelected())
    {
        test += " Dinner";
    }
    if(ExtraTrip.isSelected())
    {
        test += " Extra Trip";
    }
    
    jLDetails.setText(test);
}
private void BreakfastStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_BreakfastStateChanged
    updateOptions();
}//GEN-LAST:event_BreakfastStateChanged

private void DinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_DinnerStateChanged
    updateOptions();
}//GEN-LAST:event_DinnerStateChanged

private void ExtraTripStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ExtraTripStateChanged
    updateOptions();
}//GEN-LAST:event_ExtraTripStateChanged

private void JRBSimpleStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_JRBSimpleStateChanged
    jLRoom.setText("Simple");
}//GEN-LAST:event_JRBSimpleStateChanged

private void JRBDoubleStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_JRBDoubleStateChanged
    jLRoom.setText("Double");
}//GEN-LAST:event_JRBDoubleStateChanged

private void JRBSuiteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_JRBSuiteStateChanged
    jLRoom.setText("Suite");
}//GEN-LAST:event_JRBSuiteStateChanged

private void jRBALArabItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRBALArabItemStateChanged
    currentSelected = 0;
    jLHotel.setText("AL Arab Hotel");
}//GEN-LAST:event_jRBALArabItemStateChanged

private void jRBHiltonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRBHiltonItemStateChanged
    currentSelected = 1;
    jLHotel.setText("Hilton Hotel");
}//GEN-LAST:event_jRBHiltonItemStateChanged

private void jRBIceHotelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRBIceHotelItemStateChanged
    currentSelected = 2;
    jLHotel.setText("Ice Hotel");
}//GEN-LAST:event_jRBIceHotelItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lab5_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lab5_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lab5_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lab5_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new lab5_1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Breakfast;
    private javax.swing.JCheckBox Dinner;
    private javax.swing.JCheckBox ExtraTrip;
    private javax.swing.JRadioButton JRBDouble;
    private javax.swing.JRadioButton JRBSimple;
    private javax.swing.JRadioButton JRBSuite;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jBShowIcon;
    private javax.swing.JLabel jLDetails;
    private javax.swing.JLabel jLHotel;
    private javax.swing.JLabel jLRoom;
    private javax.swing.JLabel jLRoomIcon;
    private javax.swing.JPanel jPDetails;
    private javax.swing.JPanel jPHotel;
    private javax.swing.JPanel jPReport;
    private javax.swing.JPanel jPRoom;
    private javax.swing.JRadioButton jRBALArab;
    private javax.swing.JRadioButton jRBHilton;
    private javax.swing.JRadioButton jRBIceHotel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
